import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CTA from "@/components/CTA";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const manrope = Manrope({
  // variable: "--font-manrope",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        //  className={`${manrope.variable} ${geistMono.variable} antialiased `}
        className={manrope.className}
      >
        <Navbar/>
        {children}
        <CTA/>
         <Footer/>
      </body>
    </html>
  );
}
